GRANT USAGE, CREATE ON SCHEMA public TO :"ddl_user";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO :"ddl_user";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO :"ddl_user";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO :"ddl_user";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO :"ddl_user";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO :"ddl_user";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO :"ddl_user";
